// Generated by gencpp from file pi_robot/Distance.msg
// DO NOT EDIT!


#ifndef PI_ROBOT_MESSAGE_DISTANCE_H
#define PI_ROBOT_MESSAGE_DISTANCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pi_robot
{
template <class ContainerAllocator>
struct Distance_
{
  typedef Distance_<ContainerAllocator> Type;

  Distance_()
    : front(0)
    , left(0)
    , right(0)  {
    }
  Distance_(const ContainerAllocator& _alloc)
    : front(0)
    , left(0)
    , right(0)  {
  (void)_alloc;
    }



   typedef int16_t _front_type;
  _front_type front;

   typedef int16_t _left_type;
  _left_type left;

   typedef int16_t _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::pi_robot::Distance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pi_robot::Distance_<ContainerAllocator> const> ConstPtr;

}; // struct Distance_

typedef ::pi_robot::Distance_<std::allocator<void> > Distance;

typedef boost::shared_ptr< ::pi_robot::Distance > DistancePtr;
typedef boost::shared_ptr< ::pi_robot::Distance const> DistanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pi_robot::Distance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pi_robot::Distance_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pi_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'pi_robot': ['/home/pi/catkin_ws/src/pi_robot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pi_robot::Distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pi_robot::Distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pi_robot::Distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pi_robot::Distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pi_robot::Distance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pi_robot::Distance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pi_robot::Distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "145c935186550897a7e4b51128ea594e";
  }

  static const char* value(const ::pi_robot::Distance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x145c935186550897ULL;
  static const uint64_t static_value2 = 0xa7e4b51128ea594eULL;
};

template<class ContainerAllocator>
struct DataType< ::pi_robot::Distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pi_robot/Distance";
  }

  static const char* value(const ::pi_robot::Distance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pi_robot::Distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 front\n\
int16 left\n\
int16 right\n\
";
  }

  static const char* value(const ::pi_robot::Distance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pi_robot::Distance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.front);
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Distance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pi_robot::Distance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pi_robot::Distance_<ContainerAllocator>& v)
  {
    s << indent << "front: ";
    Printer<int16_t>::stream(s, indent + "  ", v.front);
    s << indent << "left: ";
    Printer<int16_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<int16_t>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PI_ROBOT_MESSAGE_DISTANCE_H
