// Generated by gencpp from file pi_robot/Serial_Send.msg
// DO NOT EDIT!


#ifndef PI_ROBOT_MESSAGE_SERIAL_SEND_H
#define PI_ROBOT_MESSAGE_SERIAL_SEND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pi_robot
{
template <class ContainerAllocator>
struct Serial_Send_
{
  typedef Serial_Send_<ContainerAllocator> Type;

  Serial_Send_()
    : info()  {
    }
  Serial_Send_(const ContainerAllocator& _alloc)
    : info(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _info_type;
  _info_type info;





  typedef boost::shared_ptr< ::pi_robot::Serial_Send_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pi_robot::Serial_Send_<ContainerAllocator> const> ConstPtr;

}; // struct Serial_Send_

typedef ::pi_robot::Serial_Send_<std::allocator<void> > Serial_Send;

typedef boost::shared_ptr< ::pi_robot::Serial_Send > Serial_SendPtr;
typedef boost::shared_ptr< ::pi_robot::Serial_Send const> Serial_SendConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pi_robot::Serial_Send_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pi_robot::Serial_Send_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pi_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'pi_robot': ['/home/pi/catkin_ws/src/pi_robot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pi_robot::Serial_Send_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pi_robot::Serial_Send_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pi_robot::Serial_Send_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pi_robot::Serial_Send_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pi_robot::Serial_Send_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pi_robot::Serial_Send_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pi_robot::Serial_Send_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c10fc26d5cca9a4b9114f5fc5dea9570";
  }

  static const char* value(const ::pi_robot::Serial_Send_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc10fc26d5cca9a4bULL;
  static const uint64_t static_value2 = 0x9114f5fc5dea9570ULL;
};

template<class ContainerAllocator>
struct DataType< ::pi_robot::Serial_Send_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pi_robot/Serial_Send";
  }

  static const char* value(const ::pi_robot::Serial_Send_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pi_robot::Serial_Send_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string info\n\
";
  }

  static const char* value(const ::pi_robot::Serial_Send_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pi_robot::Serial_Send_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Serial_Send_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pi_robot::Serial_Send_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pi_robot::Serial_Send_<ContainerAllocator>& v)
  {
    s << indent << "info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PI_ROBOT_MESSAGE_SERIAL_SEND_H
